### ISSUE TITLE
Colored task name in log

### ISSUE THREAD

**Issue by neckhair** [neckhair/gcron#22]
The log is currently a bit hard to overview. Logs are prefixed with their task name. But when more then one task is running it's a bit difficult the see logs which belong together.
Each task should get a random color and whenever the task logs something, its name should be written in that color.

**Comment by wafendy** [comment]
Can I take this one?

**Comment by neckhair** [comment]
@wafendy Sure. 
I imagined something like:
```
[task name] some log info
```
Where "task name" is printed in the task specific color. 
Maybe just predefine about 10 different colors and pick one for each task. (by index in the config file)
