### ISSUE TITLE
error on run

### ISSUE THREAD

**Issue by igoooor** [neckhair/gcron#23]
the two commands to run the container give me the following error
`standard_init_linux.go:185: exec user process caused "exec format error"`

I tried with those commands:
`docker run -v $(pwd)/crontainer.yml:/etc/crontainer.yml neckhair/crontainer:0.2.0`
`docker run neckhair/crontainer:0.2.0 --command="echo 'Hello World'" --schedule="*/5 * * * * *" `

Is it just me, or is it a general error?

**Comment by igoooor** [comment]
I guess this is due to the very last line of the Dockerfile, because the file "/etc/gcron.yml" doesn't exist

**Comment by neckhair** [comment]
Thanks for reporting. There were indeed some issues with the build pipeline. It's not how it should be at the moment. But the issue should be fixed now.

```
docker run -v $(pwd)/examples/crontainer.yml:/etc/crontainer.yml neckhair/crontainer:0.3.1
```
